@startuml
'https://plantuml.com/activity-diagram-beta

start
:fibonacciIterative(int n);
if (n < 0) then (true)
:throw new IllegalArgumentException("Input should be >= 0");
stop
endif

if (n > 92) then (true)
:throw new IllegalArgumentException("Input should be <= 92");
stop
endif
if (n <= 1) then (true)
:return n;
stop
endif
:return fibonacciRecursive(n - 1) + fibonacciRecursive(n - 2);
stop

@enduml
