@startuml
'https://plantuml.com/activity-diagram-beta

start
:fibonacciIterative(int n);
if (n < 0) then (true)
:throw new IllegalArgumentException("Input should be >= 0");
stop
endif

if (n > 92) then (true)
:throw new IllegalArgumentException("Input should be <= 92");
stop
endif
if (n == 0) then (true)
: return 0;
stop
endif
if (n <= 2) then (true)
: return 1L;
stop
endif

:fibonacciNumbers.add(1L)
 fibonacciNumbers.add(1L);
:i = 2;
if (i <= n) then (true)
:fibonacciNumbers.add(fibonacciNumbers.get(i - 1)
 + fibonacciNumbers.get(i - 2));
 endif
 :return fibonacciNumbers.get(n-1);
 stop




@enduml
