@startuml
'https://plantuml.com/activity-diagram-beta
start
:fibonacciIterative(int n);
if (n < 0) then (true)
:throw new IllegalArgumentException("Input should be >= 0");
stop
endif

if (n > 92) then (true)
:throw new IllegalArgumentException("Input should be <= 92");
stop
endif
if (n <= 1) then (true)
:return n;
stop
endif

if(fibonacciNumbersDP.containsKey(n)) then (true)
:return fibonacciNumbersDP.get(n);
stop
endif
:long fibonacciNumber = fibonacciDP(n - 1) + fibonacciDP(n - 2);
:fibonacciNumbersDP.put(n, fibonacciNumber);
:return fibonacciNumber;
stop









@enduml
